const noop = () => {};
const noopAsync = async () => {};
const nullHook = () => null;
const emptyObj = () => ({});

export const useShell = emptyObj;
export const useShellBridge = nullHook;
export const ShellContext = { Provider: ({ children }) => children };
export const useIdentity = () => ({ user: null, isAuthenticated: false, isLoading: false });
export const useTenant = () => ({ tenants: [], currentTenant: null, switchTenant: noop, isLoading: false });
export const useOrganization = () => ({ orgs: [], currentOrg: null, switchOrg: noop, isLoading: false });
export const useEntitlements = () => ({ permissions: [], hasPermission: () => false, isLoading: false });
export const useModules = () => ({ enabledModules: [], isModuleEnabled: () => false, toggleModule: noopAsync, isLoading: false });
export const useFeatureFlags = () => ({ featureFlags: {}, isFeatureFlagEnabled: () => false, effectiveFlags: {}, isFeatureEnabled: () => true, isFeatureReadOnly: () => false, isFeatureHidden: () => false });
export const useActivity = () => ({ recordActivity: noopAsync });
export const useNotify = () => ({ emitNotification: noopAsync });
export const useBusinessSettings = () => ({ settings: null, isLoading: false, refresh: noopAsync });
export const useQuota = () => ({ getQuota: () => null, isExceeded: () => false, isLoading: false });
export const useSandboxLimit = () => ({ isSandboxMode: false, sandboxEntryLimit: null, limitItems: (items) => items, isLimited: () => false });
export const usePageEntitlement = () => ({ entitlement: 'enabled', isBlocked: false, isLocked: false });
export const useRoiConfig = () => ({ roiConfig: null, upgradeMessages: {}, industryKey: null });
export const useStore = () => ({ stores: [], currentStore: null, switchStore: noop, isLoading: false, canCreateStore: true });
export const useTheme = () => ({ theme: 'light', toggleTheme: noop });
export const usePeople = () => ({ people: [], isLoading: false });
export const usePagination = () => ({ page: 1, pageSize: 20, setPage: noop, setPageSize: noop });
export const useSorting = () => ({ sortKey: null, sortDirection: 'asc', setSortKey: noop });
export const useFilters = () => ({ filters: {}, setFilter: noop, clearFilters: noop });
export const useVocabulary = () => ({ t: (k) => k });
export const useSubscription = () => ({ plan: null, isLoading: false });
export const Can = ({ children }) => children;
export const eventBus = { publish: noop, subscribe: () => noop };
export default {};
