import React from 'react';

const createIcon = (name: string) => {
  const Icon = (props: any) => React.createElement('svg', { 'data-testid': `icon-${name}`, ...props });
  Icon.displayName = name;
  return Icon;
};

export const AlertCircle = createIcon('AlertCircle');
export const AlertTriangle = createIcon('AlertTriangle');
export const Armchair = createIcon('Armchair');
export const ArrowLeft = createIcon('ArrowLeft');
export const ArrowRight = createIcon('ArrowRight');
export const ArrowRightLeft = createIcon('ArrowRightLeft');
export const ArrowDownLeft = createIcon('ArrowDownLeft');
export const ArrowUpRight = createIcon('ArrowUpRight');
export const BarChart3 = createIcon('BarChart3');
export const BookOpen = createIcon('BookOpen');
export const Box = createIcon('Box');
export const Building2 = createIcon('Building2');
export const Calendar = createIcon('Calendar');
export const Camera = createIcon('Camera');
export const Car = createIcon('Car');
export const Check = createIcon('Check');
export const CheckCircle2 = createIcon('CheckCircle2');
export const ChevronDown = createIcon('ChevronDown');
export const ChevronRight = createIcon('ChevronRight');
export const ChevronUp = createIcon('ChevronUp');
export const Clock = createIcon('Clock');
export const Cpu = createIcon('Cpu');
export const DollarSign = createIcon('DollarSign');
export const Edit2 = createIcon('Edit2');
export const Factory = createIcon('Factory');
export const FileText = createIcon('FileText');
export const Filter = createIcon('Filter');
export const Flame = createIcon('Flame');
export const Hammer = createIcon('Hammer');
export const History = createIcon('History');
export const Home = createIcon('Home');
export const Image = createIcon('Image');
export const ImageIcon = createIcon('ImageIcon');
export const Layers = createIcon('Layers');
export const Loader2 = createIcon('Loader2');
export const MapPin = createIcon('MapPin');
export const Monitor = createIcon('Monitor');
export const Package = createIcon('Package');
export const Paperclip = createIcon('Paperclip');
export const Pencil = createIcon('Pencil');
export const Plus = createIcon('Plus');
export const RefreshCcw = createIcon('RefreshCcw');
export const Save = createIcon('Save');
export const ScanLine = createIcon('ScanLine');
export const Search = createIcon('Search');
export const Settings = createIcon('Settings');
export const Shirt = createIcon('Shirt');
export const Sliders = createIcon('Sliders');
export const Smartphone = createIcon('Smartphone');
export const Tag = createIcon('Tag');
export const Trash2 = createIcon('Trash2');
export const TrendingDown = createIcon('TrendingDown');
export const TrendingUp = createIcon('TrendingUp');
export const Truck = createIcon('Truck');
export const Tv = createIcon('Tv');
export const Upload = createIcon('Upload');
export const UtensilsCrossed = createIcon('UtensilsCrossed');
export const Wrench = createIcon('Wrench');
export const X = createIcon('X');
export const Info = createIcon('Info');

export type LucideIcon = any;
