/**
 * Bulk import maps images to products by product name (SKU is generated by the
 * system). Keys must match the backend's (`nameKey` in csv-parser.service.ts):
 * trimmed, lower-cased, inner whitespace collapsed. Exact match only.
 */
export function nameKey(s: string | undefined | null): string {
    return (s ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
}

/** Key of an image filename: last extension removed, then normalized. */
export function nameKeyFromFilename(filename: string): string {
    return nameKey(filename.replace(/\.[^./\\]+$/, ''));
}

/** The product-name key of a parsed CSV row. */
export function rowNameKey(row: { data: Record<string, any> }): string {
    return row.data.name_key ?? nameKey(row.data.name);
}

export type ImageMatch = 'matched' | 'no_match' | 'ambiguous' | 'duplicate_image';

export function countKeys(keys: string[]): Map<string, number> {
    const counts = new Map<string, number>();
    for (const k of keys) counts.set(k, (counts.get(k) ?? 0) + 1);
    return counts;
}

/**
 * Safe, deterministic image → product decision.
 *  - no importable row with that name        → no_match
 *  - several importable rows share the name  → ambiguous (never guess)
 *  - several files share the name            → duplicate_image
 */
export function classifyImage(
    key: string,
    rowKeyCounts: Map<string, number>,
    fileKeyCounts: Map<string, number>,
): ImageMatch {
    const rows = rowKeyCounts.get(key) ?? 0;
    if (!key || rows === 0) return 'no_match';
    if (rows > 1) return 'ambiguous';
    if ((fileKeyCounts.get(key) ?? 0) > 1) return 'duplicate_image';
    return 'matched';
}

/** Counts of name keys over the rows that can actually be imported. */
export function importableRowKeyCounts(rows: { status: string; data: Record<string, any> }[]): Map<string, number> {
    return countKeys(rows.filter(r => r.status !== 'error').map(rowNameKey).filter(Boolean));
}
